apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: caller-app-service
spec:
  selector: # this selector defines which pod will be connected using this service
    app: caller-app
  
  ports:
    - name: http
      port: 9000 # incoming request on port
      nodePort: 30001
      # targetPort: 9000 # pod's container port
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: responder-app-service
spec:
  selector: # this selector defines which pod will be connected using this service
    app: responder-app
  
  ports:
    - name: http
      port: 9000 # incoming request on port
      targetPort: 9000 # pod's container port
  type: ClusterIP
