apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: caller-app
      context: caller-app
      docker:
        dockerfile: Dockerfile
      sync:
        '**/*.js': .
    - image: responder-app
      context: responder-app
      docker:
        dockerfile: Dockerfile
      sync:
        '**/*.js': .
deploy:
  kubectl:
    manifests:
      - k8s/microservices-deployment.yaml
      - k8s/microservices-service.yaml
