# local storage - mongo-persistent-volume-claim
# what do we want
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-persistent-volume-claim
spec:
  storageClassName: mylocalstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
# how do we want to be implemented
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  storageClassName: mylocalstorage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/some/anokha/path"
    type: DirectoryOrCreate